<?php
namespace Gorazd\Gorazd;
use \Gorazd\System as Sys;

/**
 * Script for working with initial SQL DB structure for Gorazd system
 * @author niwi.cz
 * @date 13.10.2013
 */
class GorazdInitController extends \Gorazd\Virtual\MainController
{
  # different URL for the form target (downloading SQL)
  public $allowTails = array('gorazd-init.sql'); #same as SQL_FILENAME
  const SQL_FILENAME = 'gorazd-init.sql';
  
  # basic tables to export
  static $TABLES = array(
    'error404', 'TOK',
    'visit', 'visitPage',
    'history', 'historyRecord',
    'website', 'section', 'page', 'menuItem',
    'person', 'user', 'permission',
    'errorLog', 'schedule',# 'mail', 'mailRecipient',
    'personDetail', 'personRelation', 'personSetting', 'personView',
    'articlesCategory', 'article',
    'comment', 'event',
    'version', 'ticket', 'ticketAssignement'
    );
  
  /**
   * Prepares data to display.
   */
  protected function prepareData()
  {
    $f = new \Gorazd\FormsBasic\FormBuilder('generate-init', 'SQL init script parameters');
    $f->targetAction = Sys\Env::urlAppend(self::SQL_FILENAME);
    $f->addInput('websiteUrl', 'Your website URL (ex. "mydomain.com")', 128);
    #TODO add HTTPS
    $f->addSubmit('Download SQL script');
    
    if ($f->isSubmitted())
    {
      preg_match('@^(https?://)?(.*)/?$@', $f->val('websiteUrl'), $matches);  # always matches
      $sql = $this->getSql($matches[2]);
      if ($sql !== false)
      {
        header('Content-type: text/sql');
        exit($sql);
      }
    }
    else if (Sys\Env::isActualTail(self::SQL_FILENAME))
      Sys\Env::redirect(Sys\Env::$urlWithoutTail);
    
    $this->customContent .= $f;
  }
  
  /**
   *
   */
  private function getSql ($websiteUrl)
  {
    $thisPage = Sys\Env::$urlWithoutTail;
    $now = Sys\Utils::now();
    $sql = <<<EOT
--
-- SQL dump of required tables for Gorazd system
-- Generated by script on the page $thisPage
-- Date: $now
--

SET AUTOCOMMIT = 0;
START TRANSACTION;\n\n
EOT;
    
    # dump table structures
    $dbname = conf('dbDatabase');
    foreach (self::$TABLES as $table)
    {
      $type = $table == 'personView' ? 'VIEW' : 'TABLE';
      $res = Sys\Db::query("SHOW CREATE $type `$dbname`.`$table`");
      if (!$res)
        return err('Interní chyba při práci s daty', 2, 'Chyba při zjišťování struktury tabulky '.$table);
      $row = $res->fetch_row();
      if ($row)
      {
        # throw off auto increment
        $struct = preg_replace('/AUTO_INCREMENT=\d+/', 'AUTO_INCREMENT=1', $row[1]);
        // throw off superadmin params in view
        if ($table == 'personView')
        {
          $struct = preg_replace('$ALGORITHM=.*SECURITY DEFINER$', '', $struct);
        }
        $sql .= <<<EOT
-- ----------------------------------------
-- Structure of the table $table
-- ----------------------------------------
$struct;\n\n
EOT;
      }
      else
        msg('Nepodařilo se načíst informace o tabulce '.$table, MSG_ERROR);
    }
    
    
    # add TOK values
    $sql .= <<<EOT
-- ----------------------------------------
-- Data from table TOK
-- ----------------------------------------
INSERT INTO `TOK` (`key`, `value`, `type`) VALUES\n
EOT;
    $res = Sys\Db::query("SELECT * FROM TOK WHERE `key` < 1000 ORDER BY `key`");
    $tokStrings = array();
    while ($row = $res->fetch_assoc())
      $tokStrings[] = "(". esc($row['key']) .", '". esc($row['value']) ."', '". esc($row['type']) ."')";
    $sql .= implode(",\n", $tokStrings) . ";\n\n";

    
    # insert other values
    $sql .= <<<EOT
-- add website
INSERT INTO `website` (`id`, `name`, `title`)
  VALUES (1, '$websiteUrl', '$websiteUrl');

-- add the main page
INSERT INTO `page` (`id`, `title`, `content`, `controller`, `readPermission`, `writePermission`)
  VALUES (1,'Úvodní strana', '<p>Vítejte na úvodní stránce webu!</p>', 'WebAdmin\InitController', 0, 5);
INSERT INTO `menuItem` (`pageId`, `websiteId`, `url`, `rank`)
  VALUES (1, 1, '', 1);

-- add MenuController
INSERT INTO `page` (`id`, `title`, `content`, `controller`, `readPermission`, `writePermission`)
   VALUES (2, 'Struktura webu', 'Pomocí struktury menu níže je možné upravovat jednotlivé stránky a menu.', 'WebAdmin\MenuController', 5, 5);
INSERT INTO `menuItem` (`pageId`, `websiteId`, `url`, `rank`)
  VALUES (2, 1, 'struktura-webu', 1);

EOT;
    
    return $sql;
  }
}
?>
